# Generated by Django 3.1.7 on 2021-08-23 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('template', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(blank=True, max_length=254, null=True)),
                ('campaign_title', models.CharField(blank=True, max_length=250, null=True)),
                ('start_date', models.CharField(blank=True, max_length=250, null=True)),
                ('end_date', models.CharField(blank=True, max_length=240, null=True)),
                ('target_users_mail_list', models.TextField(blank=True, null=True)),
                ('campaign_opened_count', models.IntegerField(blank=True, default=0)),
                ('hide_camapaign_status', models.BooleanField(default=False)),
                ('campaign_schedule_status', models.BooleanField(default=False)),
                ('start_time', models.CharField(blank=True, max_length=150, null=True)),
                ('campaign_email_detail_message', models.CharField(blank=True, max_length=254, null=True)),
                ('camapign_email_title_message', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetUserCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvs')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TargetUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(blank=True, max_length=254, null=True)),
                ('organization', models.CharField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TargetUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('target_user_uuid', models.UUIDField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('email_credential', models.EmailField(blank=True, max_length=254, null=True)),
                ('password_credential', models.CharField(blank=True, max_length=254, null=True)),
                ('leaked_password_credential', models.CharField(blank=True, max_length=254, null=True)),
                ('user_agent_data', models.TextField(blank=True, null=True)),
                ('more_details', models.TextField(blank=True, null=True)),
                ('all_data', models.TextField(blank=True, null=True)),
                ('camapaign_opened_details', models.TextField(blank=True, null=True)),
                ('opened_campaign_list', models.ManyToManyField(blank=True, to='campaign.Campaign')),
                ('targetusergroup', models.ManyToManyField(blank=True, related_name='targetuser', to='campaign.TargetUserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_date', models.CharField(blank=True, max_length=254, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
                ('targetuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.targetuser')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='targetusergroup',
            field=models.ManyToManyField(related_name='campaign', to='campaign.TargetUserGroup'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='templateresource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.templateresource'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
