# Generated by Django 3.1.7 on 2021-08-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetuser',
            name='password_leaked_status',
            field=models.BooleanField(default=False),
        ),
    ]
