# Generated by Django 3.1.7 on 2021-04-23 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='targetuser',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.targetuser'),
            preserve_default=False,
        ),
    ]
