# Generated by Django 3.1.7 on 2021-08-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_targetuser_password_leaked_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetuser',
            name='camapaign_opened_details',
        ),
        migrations.AddField(
            model_name='targetuser',
            name='browser',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='targetuser',
            name='operating_sys',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
