# Generated by Django 3.1.7 on 2021-04-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_targetuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='campaign_template',
            new_name='template',
        ),
    ]
