# Generated by Django 3.1.7 on 2021-04-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20210423_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
