# Generated by Django 3.1.7 on 2021-08-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20210824_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetuser',
            name='all_data',
        ),
        migrations.RemoveField(
            model_name='targetuser',
            name='more_details',
        ),
    ]
