# Generated by Django 3.1.7 on 2021-08-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20210824_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetuser',
            name='associated_campaign_list',
            field=models.ManyToManyField(blank=True, related_name='associated_campaign', to='campaign.Campaign'),
        ),
        migrations.AlterField(
            model_name='targetuser',
            name='opened_campaign_list',
            field=models.ManyToManyField(blank=True, related_name='opened_campaign', to='campaign.Campaign'),
        ),
    ]
