# Generated by Django 3.1.7 on 2021-08-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20210824_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignstatus',
            old_name='campaign_date',
            new_name='campaign_opened_date',
        ),
        migrations.RemoveField(
            model_name='targetuser',
            name='status',
        ),
        migrations.AddField(
            model_name='targetuser',
            name='campaign_opened_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='targetuser',
            name='email_opened_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='targetuser',
            name='target_user_uuid',
            field=models.UUIDField(),
        ),
    ]
