# Generated by Django 3.1.7 on 2021-04-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_auto_20210423_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='targetuser',
        ),
        migrations.AddField(
            model_name='campaign',
            name='targetuser',
            field=models.ManyToManyField(to='campaign.TargetUser'),
        ),
    ]
