# Generated by Django 3.1.7 on 2021-08-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_auto_20210828_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignstatus',
            name='campaign_opened_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetuser',
            name='campaign_opened_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='targetuser',
            name='email_opened_status',
            field=models.BooleanField(default=False),
        ),
    ]
