# Generated by Django 3.1.7 on 2021-04-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_auto_20210423_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
