# Generated by Django 3.1.7 on 2021-08-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_auto_20210828_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='start_time',
            field=models.TimeField(blank=True, max_length=150, null=True),
        ),
    ]
