# Generated by Django 3.1.7 on 2021-04-26 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0008_auto_20210425_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetuser',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel'),
            preserve_default=False,
        ),
    ]
