# Generated by Django 3.1.7 on 2021-08-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_auto_20210828_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='start_time',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
