# Generated by Django 3.1.7 on 2021-08-28 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_userlogger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogger',
            old_name='action_type',
            new_name='action',
        ),
        migrations.RemoveField(
            model_name='userlogger',
            name='time',
        ),
        migrations.AddField(
            model_name='userlogger',
            name='dateandtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
