# Generated by Django 3.1.7 on 2021-04-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_auto_20210427_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(default='camp', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
