# Generated by Django 3.1.7 on 2021-08-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_auto_20210828_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogger',
            name='request_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
