# Generated by Django 3.1.7 on 2021-09-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_userlogger_request_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='targetusergroup',
            name='group_name',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
