# Generated by Django 3.1.7 on 2021-04-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_auto_20210427_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
