# Generated by Django 3.1.7 on 2021-05-04 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0014_auto_20210430_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetuser',
            name='username',
        ),
    ]
