# Generated by Django 3.1.7 on 2021-05-05 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0015_remove_targetuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='targetuser',
        ),
        migrations.RemoveField(
            model_name='targetuser',
            name='user',
        ),
        migrations.CreateModel(
            name='TargetUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(blank=True, max_length=254, null=True)),
                ('organization', models.CharField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='targetusergroup',
            field=models.ManyToManyField(to='campaign.TargetUserGroup'),
        ),
        migrations.AddField(
            model_name='targetuser',
            name='targetusergroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.targetusergroup'),
            preserve_default=False,
        ),
    ]
