# Generated by Django 3.1.7 on 2021-05-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0016_auto_20210505_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targetuser',
            old_name='targetusergroup',
            new_name='group',
        ),
    ]
