# Generated by Django 3.1.7 on 2021-05-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0017_auto_20210505_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetuser',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
