# Generated by Django 3.1.7 on 2021-05-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0018_auto_20210505_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targetuser',
            old_name='group',
            new_name='targetusergroup',
        ),
        migrations.RenameField(
            model_name='targetusergroup',
            old_name='group',
            new_name='group_name',
        ),
    ]
