# Generated by Django 3.1.7 on 2021-05-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0019_auto_20210505_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
