# Generated by Django 3.1.7 on 2021-05-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0021_targetusercsv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetuser',
            name='targetusergroup',
        ),
        migrations.AddField(
            model_name='targetusergroup',
            name='targetuser',
            field=models.ManyToManyField(to='campaign.TargetUser'),
        ),
    ]
