# Generated by Django 3.1.7 on 2021-05-09 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0022_auto_20210509_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetusergroup',
            name='targetuser',
        ),
        migrations.AddField(
            model_name='targetuser',
            name='targetusergroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.targetusergroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='targetusercsv',
            name='file_name',
            field=models.FileField(default=1, upload_to='csvs'),
            preserve_default=False,
        ),
    ]
