# Generated by Django 3.1.7 on 2021-05-09 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0024_auto_20210509_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetuser',
            name='targetusergroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetuser', to='campaign.targetusergroup'),
        ),
    ]
