# Generated by Django 3.1.7 on 2021-05-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0025_auto_20210509_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='target_users_mail_list',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
