# Generated by Django 3.1.7 on 2021-05-21 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0026_campaign_target_users_mail_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetuser',
            name='targetusergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targetuser', to='campaign.targetusergroup'),
        ),
    ]
