# Generated by Django 3.1.7 on 2021-05-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0027_auto_20210521_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetuser',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='targetuser',
            name='target_user_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
