# Generated by Django 3.1.7 on 2021-05-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0028_auto_20210527_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RemoveField(
            model_name='targetuser',
            name='targetusergroup',
        ),
        migrations.AddField(
            model_name='targetuser',
            name='targetusergroup',
            field=models.ManyToManyField(to='campaign.TargetUserGroup'),
        ),
    ]
