# Generated by Django 3.1.7 on 2021-05-27 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0029_auto_20210527_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetuser',
            name='targetusergroup',
        ),
        migrations.AddField(
            model_name='targetuser',
            name='targetusergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targetuser', to='campaign.targetusergroup'),
        ),
    ]
