# Generated by Django 3.1.7 on 2021-05-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0033_auto_20210528_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetusergroup',
            name='targetuser',
        ),
        migrations.AddField(
            model_name='targetuser',
            name='targetusergroup',
            field=models.ManyToManyField(blank=True, null=True, related_name='targetuser', to='campaign.TargetUserGroup'),
        ),
    ]
