# Generated by Django 3.1.7 on 2021-05-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0034_auto_20210528_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetuser',
            name='opened_campaign_list',
            field=models.ManyToManyField(to='campaign.Campaign'),
        ),
    ]
