# Generated by Django 3.1.7 on 2021-06-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0035_targetuser_opened_campaign_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetuser',
            name='email_credential',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='targetuser',
            name='password_credential',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='targetusergroup',
            field=models.ManyToManyField(related_name='campaign', to='campaign.TargetUserGroup'),
        ),
        migrations.AlterField(
            model_name='targetuser',
            name='opened_campaign_list',
            field=models.ManyToManyField(blank=True, to='campaign.Campaign'),
        ),
        migrations.AlterField(
            model_name='targetuser',
            name='targetusergroup',
            field=models.ManyToManyField(blank=True, related_name='targetuser', to='campaign.TargetUserGroup'),
        ),
    ]
