# Generated by Django 3.1.7 on 2021-06-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0036_auto_20210601_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetuser',
            name='email_credential',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='targetuser',
            name='password_credential',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
