# Generated by Django 3.1.7 on 2021-06-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0037_auto_20210601_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetuser',
            name='email_credential',
        ),
        migrations.RemoveField(
            model_name='targetuser',
            name='password_credential',
        ),
    ]
