# Generated by Django 3.1.7 on 2021-06-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0038_auto_20210601_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetuser',
            name='email_credential',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='targetuser',
            name='password_credential',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
