# Generated by Django 3.1.7 on 2021-06-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0039_auto_20210601_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetuser',
            name='email_credential',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
