# Generated by Django 3.1.7 on 2021-06-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0041_auto_20210601_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetuser',
            name='password_credential',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
