# Generated by Django 3.1.7 on 2021-06-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0042_auto_20210601_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetuser',
            name='status',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_opened_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
