# Generated by Django 3.1.7 on 2021-06-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0043_auto_20210602_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_opened_count',
        ),
        migrations.AddField(
            model_name='targetuser',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
