# Generated by Django 3.1.7 on 2021-06-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0044_auto_20210602_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_opened_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
