# Generated by Django 3.1.7 on 2021-06-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0045_campaign_campaign_opened_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetuser',
            name='password_credential',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
