# Generated by Django 3.1.7 on 2021-06-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0046_auto_20210602_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetuser',
            name='leaked_password_credential',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
