# Generated by Django 3.1.7 on 2021-06-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0047_targetuser_leaked_password_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='hide_camapaign_status',
            field=models.BooleanField(default=False),
        ),
    ]
