# Generated by Django 3.1.7 on 2021-06-06 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '__first__'),
        ('campaign', '0048_campaign_hide_camapaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='templateresource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.templateresource'),
        ),
    ]
