# Generated by Django 3.1.7 on 2021-06-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0049_auto_20210606_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_schedule_status',
            field=models.BooleanField(default=False),
        ),
    ]
