# Generated by Django 3.1.7 on 2021-06-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0050_campaign_campaign_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='target_users_mail_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
