# Generated by Django 3.1.7 on 2021-06-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0051_auto_20210615_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetuser',
            name='user_agent_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
