# Generated by Django 3.1.7 on 2021-06-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0052_targetuser_user_agent_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetuser',
            name='all_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetuser',
            name='mode_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
