# Generated by Django 3.1.7 on 2021-06-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0053_auto_20210623_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targetuser',
            old_name='mode_details',
            new_name='more_details',
        ),
    ]
