# Generated by Django 3.1.7 on 2021-06-25 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0054_auto_20210623_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetuser',
            name='all_data',
        ),
    ]
