# Generated by Django 3.1.7 on 2021-06-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0055_remove_targetuser_all_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetuser',
            name='all_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
